[package]
name = "flight-usa-categoriser"
version = "0.2.0"
authors = ["blakehawkins"]
edition = "2018"

[dependencies]
phf = { version = "0.8.0", features = ["macros"] }
oops = "0.1"
stdinix = "0.1"

