[package]
name = "flight-usa-categoriser"
version = "0.2.0"
authors = ["blakehawkins"]
edition = "2018"

[dependencies]
csv = "1.1"
getopt = "1.1"
phf = { version = "0.8.0", features = ["macros"] }
oops = "0.2"
