[package]
name = "flight-usa-categoriser"
version = "0.1.0"
authors = ["blake"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = { version = "0.8.0", features = ["macros"] }
